apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  selector:
    app: "{{ .Release.Name }}"
  type: NodePort
  ports:
    - name: app1
      port: 3001
      targetPort: 3001
      nodePort: 31001
