services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend-server
    restart: always
    environment:
      - NODE_ENV=test
      - DATABASE_URL=mysql://root:root@mysql:3306/test
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    external: true
